### PR TITLE
Add example for duplicate-paths test showing rendered log results.

### PR DESCRIPTION
**Pull request by gkellogg**
I added a render of the result of running the duplicate paths test to see how this might look. It results in fairly deep nesting, and I'm not sure it's too useful for the average reader, but might help others.

```turtle
BASE <http://example.com/>
PREFIX : <#>

_:e0 :p1 _:e1 .
_:e1 :p2 "Foo" .
_:e2 :p1 _:e3 .
_:e3 :p2 "Foo" .
```

As much as this does, there are more complicated examples that use more of the algorithm (e.g., test022).

Note that this is an update to PR #63. I'm not sure if it's useful enough to include.

Because this uses data-include, it won't actually show up in PR preview, so you can see it using GitHack [here](https://raw.githack.com/w3c/rdf-canon/duplicated-paths-example/spec/index.html).

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-canon/pull/64.html" title="Last updated on Jan 12, 2023, 1:32 AM UTC (20b6bb9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-canon/64/84db619...20b6bb9.html" title="Last updated on Jan 12, 2023, 1:32 AM UTC (20b6bb9)">Diff</a>

### CODE REVIEW

**Comment by gkellogg** [comment]
Here's another output for [test022](https://raw.githack.com/ruby-rdf/rdf-normalize/develop/examples/test022.html).

**Review by dlongley — APPROVED** [review]
I noticed that the HTML rendering of the logging uses ellipsis when the value is too long sometimes ... we'll want to have a way to expand those for viewing (if we already have a way, I didn't see it).

**Comment by gkellogg** [comment]
The long strings using an ellipsis are tucked in `abbr` elements, so the full value can be revealed by hovering. Perhaps there’s some active interrogation of the View area that could make this dynamic, but it’s beyond me at this point.

Even with the abbreviations, it still makes the view window pretty wide and I’m not really convinced of the value of this kind of example/trace.

More valuable for developers might be to show a YAML and HTML trace for every test, and not try to directly include in the spec.

**Comment by iherman** [comment]
> The long strings using an ellipsis are tucked in `abbr` elements, so the full value can be revealed by hovering. Perhaps there’s some active interrogation of the View area that could make this dynamic, but it’s beyond me at this point.
> 
> Even with the abbreviations, it still makes the view window pretty wide and I’m not really convinced of the value of this kind of example/trace.

Much as it is logical to nest the entries to follow the cycles, the resulting wide table is difficult to follow. I wonder whether it is not better to use this example the same way as example 7, for example, ie, some sort of verbose description of what is happening. That would help the reader to understand the essence of the algorithm without all the details of the YAML output.

> 
> More valuable for developers might be to show a YAML and HTML trace for every test, and not try to directly include in the spec.

Agreed but, actually, I am not even sure that the HTML trace is all that useful for developers. A YAML output might be enough.

**Comment by gkellogg** [comment]
> > The long strings using an ellipsis are tucked in `abbr` elements, so the full value can be revealed by hovering. Perhaps there’s some active interrogation of the View area that could make this dynamic, but it’s beyond me at this point.
> > Even with the abbreviations, it still makes the view window pretty wide and I’m not really convinced of the value of this kind of example/trace.
> 
> Much as it is logical to nest the entries to follow the cycles, the resulting wide table is difficult to follow. I wonder whether it is not better to use this example the same way as example 7, for example, ie, some sort of verbose description of what is happening. That would help the reader to understand the essence of the algorithm without all the details of the YAML output.

I was trying to get away from having to hand author each example, and instead derive something from the logs. In any case, recursion is going to be part of it, so some form of indentation is inevitable. It wasn't immediately apparent how I could interpret the YAML log into something that is less indented, but some areas of it can certainly be customized.

To illustrate all parts of the algorithm will require exploring more examples, and creating these by hand is hard work.

**Comment by gkellogg** [comment]
Although people may take issue with this example, I think it's worth merging into #63.

**Pull request merged**
