### PR TITLE
Add EARL report for RDF.ex

### PR DESCRIPTION
**Pull request by marcelotto**
Adding implementation EARL report.

Name: RDF.ex
Version: 1.2 (to be released soon)
Language: Elixir
Developer: Marcel Otto
Homepage: https://github.com/rdf-elixir/rdf-ex

### CODE REVIEW

**Comment by marcelotto** [comment]
Just noticed that the actual results are not shown in `index.html`. What do I have to do to get them included?

**Comment by davidlehn** [comment]
You only need to commit your .ttl result file.  The other files are autogenerated.  (It also looks like you used outdated tooling when you did generate those files based on the diffs.)

**Comment by gkellogg** [comment]
> Just noticed that the actual results are not shown in `index.html`. What do I have to do to get them included?

I approved running the generator which creates the index.html file. If you look at the run details, you'll see that `earl-report` is skipping a number of tests:

Run (cd reports; rake)
write
   skip earl.ttl, which seems to be a previous rollup earl report
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test045c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test021c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test061c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test077c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test003c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test059c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test017c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test010c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test023c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test070c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test019c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test026c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test006c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test039c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test036c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test005c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test065c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test076c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test034c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test060c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test053c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test066c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test022c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test040c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test046c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test048c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test062c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test011c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test001c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test056c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test054c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test025c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test028c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test027c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test057c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test004c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test035c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test063c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test029c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test038c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test047c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test068c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test071c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test018c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test055c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test069c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test008c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test073c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test024c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test064c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test016c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test033c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test067c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test058c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test013c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test020c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test009c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test030c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test014c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test044c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test072c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test043c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test002c for https://hex.pm/packages/rdf, which is not defined in manifests
Skipping result for https://github.com/w3c/rdf-canon/tests/manifest#test075c for https://hex.pm/packages/rdf, which is not defined in manifests
No results found for https://hex.pm/packages/rdf using 
    PREFIX earl: <http://www.w3.org/ns/earl#>
    
    SELECT ?test ?subject ?by ?mode ?outcome ?info
    WHERE {
      ?a a earl:Assertion;
        earl:assertedBy ?by;
        earl:result ?result;
        earl:subject ?subject;
        earl:test ?test .
      ?result earl:outcome ?outcome .
      OPTIONAL {?a earl:mode ?mode .}
      OPTIONAL {?result earl:info ?info .}
    }
    ORDER BY ?subject
  
It's probably a good idea to do a "bundle install" and run the report generator (see reports/Rakefile).

It looks like you ran with the test base of `https://github.com/w3c/rdf-canon/tests/manifest` rather than `https://w3c.github.io/rdf-canon/tests/manifest`.

**Comment by marcelotto** [comment]
> It looks like you ran with the test base of https://github.com/w3c/rdf-canon/tests/manifest rather than https://w3c.github.io/rdf-canon/tests/manifest.

That was the problem indeed. Forgot to update this when migrating from the old test suite.

**Comment by gkellogg** [comment]
For whatever reason, but update action failed to commit changes back to the source branch. At this point, best to run the rake task and commit the generated files, which would be the same as the Git Action would have done.

**Review by gkellogg — APPROVED** [review]
Once the generated files are uploaded. Congratulations and thanks for adding your implementation, Note that you did not run those tests marked `RDFC10MapTest`, which is fine for reporting purposes.

**Review by dlongley — APPROVED** [review]

**Comment by marcelotto** [comment]
> Once the generated files are uploaded. Congratulations and thanks for adding your implementation, Note that you did not run those tests marked RDFC10MapTest, which is fine for reporting purposes.

Oh, didn't notice this new class of tests. To be honest, I was a bit rushed with the migration of the test suite, as I noticed today that a whole bunch of issues were closed and therefore assumed that completion was imminent. If there is still time, I would also try to integrate the other classes of tests and get them green, which is presumably a bit more work for the `RDFC10MapTest`s.

**Comment by gkellogg** [comment]
There should be time for you to add the missing functionality; the results should already be intermediate values from your implementation.

**Pull request merged**
