### PR TITLE
Turn off hljs on logging pre sections.

### LINKED ISSUE #147: "Logging" expandos have empty context
The "Logging" content is in the spec in commented sections, but show up as empty box in the spec.

Is a more in depth explanation needed for how to interpret that logging content?

### PR DESCRIPTION
**Pull request by gkellogg**
In Chrome, this caused the exxpected log messages not to appear.

Fixes #147.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-canon/pull/154.html" title="Last updated on Jul 28, 2023, 6:21 PM UTC (b9d544c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/rdf-canon/154/84315eb...b9d544c.html" title="Last updated on Jul 28, 2023, 6:21 PM UTC (b9d544c)">Diff</a>

### CODE REVIEW

**Review by dlongley — APPROVED** [review]
Works for me.

**Comment by davidlehn** [comment]
- Also needs the fix in `common/typographical-conventions.html`.
- May be worth looking into why YAML-LD spec shows it's `<pre class="example yaml" ...>` text ok, but this logging yaml text doesn't work.  It's not highlighted in YAML-LD as YAML, but it at least shows up.
- Related to both specs is YAML is not a [default supported language](https://respec.org/docs/#pre-and-code-elements).  Looks like another highlighter could be added, but their example uses a CJS script and the highlightjs yaml code is ESM.  Maybe not worth the trouble to figure that out right now.
- The text flush to the border could be improved.  How about in `pre.logging` style adding `padding: 0.3em;`?

**Review by yamdan — APPROVED** [review]
Approving with David's comment. I usually use Firefox and didn't notice the issue.

**Comment by gkellogg** [comment]
Highlighter is part of ReSpec, probably don’t want to try to include our own. We use examples that aren’t pure YAML, anyway.

good question on why YAML-LD spec doesn’t show the issue, or why it worked on Safari.

**Comment by gkellogg** [comment]
According to the [highlight.js page](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md), YAML is a default supported language. But, there's something in ReSpec which is not rendering the result. It does pass through `updateExample` okay, but get's dropped when rendering in ReSpec. I'd consider that a bug, but don't really want to spend the time to track it down right now.

**Comment by davidlehn** [comment]
highlight.js itself supports many languages, but as the respec link I noted above says, it only enables a few by default.  I didn't dig into it enough to figure how to pull in YAML support without too much pain.  May be easier to lobby repsec to include it if other projects need YAML support too.
https://github.com/w3c/respec/blob/main/worker/respec-highlight.js

**Review by davidlehn — APPROVED** [review]

**Pull request merged**
