### PR TITLE
Remove NP-intermediate and clean up related informative text.

### PR DESCRIPTION
**Pull request by dlongley**
Addresses #122.

### CODE REVIEW

**Comment by gkellogg** [comment]
For some reason, PR preview didn't kick off for this.

**Review by gkellogg — COMMENTED** [review]
Maybe worth adding a reference to [Data Poisoning](https://www.w3.org/TR/rdf-canon/#dataset-poisoning).

**Review by iherman — APPROVED** [review]
Wholeheartedly agree with removing this. The exact theoretical characterization is not really relevant for the specification, it does not bring anything to the text.

I agree with @gkellogg's comment that a reference to the poison graphs would be good to have.

**Comment by dlongley** [comment]
Added a reference to dataset poisoning here: 6030f770810e61c399b19f114ef8e0a9f6f25a4c.

**Review by TallTed — APPROVED** [review]

**Review by yamdan — APPROVED** [review]

**Pull request merged**
