### PR TITLE
Renamed `_:b*` types names to `_:e*` in the tests

### PR DESCRIPTION
**Pull request by iherman**
In line with a [similar commit](https://github.com/w3c/rdf-canon/pull/45/commits/d57bbd9575a5b47652c02b94f2c7f76ed7b85be3) I changed all the occurences of `_:b*` blank node names to `_:e* in all the tests.

Reminder: in [Step 5.2.2.](https://www.w3.org/TR/rdf-canon/#ca-5-2-2) we create a new, temporary ID issuer with the prefix `b`. If the original nquads use this prefix (and the parser keeps these prefixes) it leads to major confusions when looking at debug logs or examples. Hence the aforementioned commit for the examples in the spec, and this PR does the same for all official tests.

### CODE REVIEW

**Comment by iherman** [comment]
Actually, test No. 59 has changed more thoroughly. The original test used fairly cryptic and difficult-to-use blank nodes; this PR aligns them to the style of the other tests.

**Comment by dlongley** [comment]
It's probably important to continue to have at least some tests that use `_:b` as a prefix to ensure that an implementation doesn't have a problem because of it.

**Review by gkellogg — APPROVED** [review]

**Review by dlongley — APPROVED** [review]
+1 to duplicating some tests to use `_:b`.

**Comment by marcelotto** [comment]
It seems it was forgotten to add test 63 to the manifests.

**Pull request merged**
